### PR TITLE
Start fri

### PR DESCRIPTION
**Pull request by starkoracles**

### CODE REVIEW

**Comment by starkoracles** [comment]
@maxgillett I had to change to 1 FRI query so it'll finish in a reasonable time, this is the trace:
```
➜  risc0_profiling_tool git:(small-changes-and-bugfixes) ✗ pipenv run python3 prof.py
(('core::fmt::num::imp::fmt_u64::he902c374f323d867', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h238c20d6b5733c49', 'winter_math::polynom::interpolate_batch::hacc61cfc1354fe3b'), 21776)
(('winter_math::fft::interpolate_poly::h5ee9269298925247', 'winter_math::fft::serial::interpolate_poly::h14e7cfee6f461b74', 'winter_math::fft::serial::fft_in_place::h3828e1f0fbbc4892'), 13876)
(('alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::h64636997e7c87cec', 'memmove', 'compiler_builtins::mem::memmove::h723f6c7b49872e97'), 11072)
(('core::fmt::num::imp::fmt_u64::he902c374f323d867', 'winter_verifier::composer::DeepComposer<E>::compose_trace_columns::h744f7c85aa9dc7e5', '<winter_math::field::f64::BaseElement as core::ops::arith::Div>::div::hdba1a2f7c158c77e'), 11032)
(('risc0_zkvm_guest::sha::digest_u8_slice::h370a9782be0cf7d6', 'memcpy', 'compiler_builtins::mem::memcpy::h999c109051d3a4ad'), 8573)
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h238c20d6b5733c49', 'winter_math::polynom::interpolate_batch::hacc61cfc1354fe3b', 'winter_math::utils::batch_inversion::hd2b3630994d2eebe'), 7722)
(('winter_fri::verifier::verify_remainder::hea88dd7740684a57', 'winter_math::fft::interpolate_poly::h5ee9269298925247', 'winter_math::fft::serial::interpolate_poly::h14e7cfee6f461b74'), 6587)
(('winter_verifier::evaluator::evaluate_constraints::hb0a0d38713a7f5f1', 'winter_air::air::boundary::constraint_group::BoundaryConstraintGroup<F,E>::evaluate_at::h510c5b3e5eb43ba9', 'winter_air::air::divisor::ConstraintDivisor<B>::evaluate_at::h5478890a3374b850'), 5924)
(('core::fmt::num::imp::fmt_u64::he902c374f323d867', 'winter_verifier::composer::DeepComposer<E>::compose_constraint_evaluations::h05406aefb018bf27', '<winter_math::field::f64::BaseElement as core::ops::arith::Div>::div::hdba1a2f7c158c77e'), 5516)
(('winter_verifier::evaluator::evaluate_constraints::hb0a0d38713a7f5f1', 'winter_air::air::boundary::constraint_group::BoundaryConstraintGroup<F,E>::evaluate_at::h510c5b3e5eb43ba9', '<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::he3fe2b39940cddb4'), 5438)
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h238c20d6b5733c49', 'winter_fri::verifier::channel::VerifierChannel::read_layer_queries::h932f17b07eb87703', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::he5e0eab89a340d50'), 5089)
(('risc0_zkvm_guest::sha::digest_u8_slice::h370a9782be0cf7d6', 'memset', 'compiler_builtins::mem::memset::h9421d27f772005d6'), 4959)
(('winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::he5e0eab89a340d50', 'alloc::collections::btree::map::BTreeMap<K,V>::insert::h643b4638afa39b85', 'alloc::collections::btree::map::entry::VacantEntry<K,V>::insert::h84c4b26bf3e0c212'), 4877)
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h238c20d6b5733c49', 'winter_math::polynom::interpolate_batch::hacc61cfc1354fe3b', 'winter_math::polynom::fill_zero_roots::h9e01c5c18591e667'), 4829)
(('<&T as core::fmt::Debug>::fmt::h70c0b3f1f446f2dc', 'core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt::h4df39a90824eddd4', 'core::fmt::num::imp::fmt_u64::he902c374f323d867'), 4792)
```

**Comment by starkoracles** [comment]
In order to get FRI to work I ended up accepting some memcpy by rkyv to end up with VerifierChannel which is compatible with most of Winter's code. I'm happy I did that because it doesn't seem to dominate the trace.

It seems like the big thing to optimize is div, interpolate, and merkle verification

**Comment by cpunkzzz** [comment]
trace with inlines disabled:
```
➜  risc0_profiling_tool git:(small-changes-and-bugfixes) ✗ pipenv run python3 prof.py
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', 'winter_math::polynom::interpolate_batch::hb8afdf01fc3a097d', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12'), 15332)
(('alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::h6f1c7cfbf12cc11f', 'memmove', 'compiler_builtins::mem::memmove::ha1d81b2d3751da88'), 11072)
(('winter_math::fft::interpolate_poly::ha4bdeb398666aa90', 'winter_math::fft::serial::interpolate_poly::h4a43566481065096', 'winter_math::fft::serial::fft_in_place::hb7a1545ee2a0eee1'), 9350)
(('winter_verifier::composer::DeepComposer<E>::compose_trace_columns::h7ea4a7c255bdf473', '<winter_math::field::f64::BaseElement as core::ops::arith::Div>::div::h3bb782ba13a1e27b', '<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::h7eac9395cb8fb2d0'), 8884)
(('risc0_zkvm_guest::sha::digest_u8_slice::h16754d6da2ff763a', 'memcpy', 'compiler_builtins::mem::memcpy::hba8731a4c8e62e30'), 8573)
(('winter_air::air::divisor::ConstraintDivisor<B>::evaluate_at::h991d68ff6850e41a', '<winter_math::field::f64::BaseElement as core::ops::arith::Div>::div::h3bb782ba13a1e27b', '<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::h7eac9395cb8fb2d0'), 6663)
(('<winter_math::field::f64::BaseElement as core::ops::arith::Div>::div::h3bb782ba13a1e27b', '<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::h7eac9395cb8fb2d0', 'winter_math::field::f64::exp_acc::h3705b31690abbccc'), 6288)
(('core::fmt::num::imp::fmt_u64::h955bda630abb3b10', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', 'winter_math::polynom::interpolate_batch::hb8afdf01fc3a097d'), 5420)
(('core::fmt::num::imp::fmt_u64::h955bda630abb3b10', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', '<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::exp::h8a2c77ac6c62f624'), 5177)
(('winter_math::fft::serial::interpolate_poly::h4a43566481065096', 'winter_math::fft::serial::fft_in_place::hb7a1545ee2a0eee1', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12'), 5120)
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', 'winter_fri::verifier::channel::VerifierChannel::read_layer_queries::hf9f1250f02f1a32d', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h4a9acce079b79dce'), 5089)
(('risc0_zkvm_guest::sha::digest_u8_slice::h16754d6da2ff763a', 'memset', 'compiler_builtins::mem::memset::h94eecc2afbdbd211'), 4959)
(('winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h4a9acce079b79dce', 'alloc::collections::btree::map::BTreeMap<K,V>::insert::h314585ca19ed9384', 'alloc::collections::btree::map::entry::VacantEntry<K,V>::insert::ha5e1b491800855d5'), 4877)
(('<&T as core::fmt::Debug>::fmt::hf587855afcc68d1c', 'core::fmt::num::imp::<impl core::fmt::Display for u64>::fmt::h6cfab8d065540efe', 'core::fmt::num::imp::fmt_u64::h955bda630abb3b10'), 4762)
(('risc0_zkvm_guest::sha::add_trailer::h7cbc5740a28e5d9b', 'memset', 'compiler_builtins::mem::memset::h94eecc2afbdbd211'), 4683)
```

**Comment by cpunkzzz** [comment]
with inlines disabled:
```
➜  risc0_profiling_tool git:(small-changes-and-bugfixes) ✗ pipenv run python3 prof.py
(('<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::h7eac9395cb8fb2d0', 'winter_math::field::f64::exp_acc::h7a5f087f9eaeea7e', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12'), 16896)
(('winter_math::field::f64::exp_acc::h7a5f087f9eaeea7e', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12', 'winter_math::field::f64::mont_red_cst::h4a0e8151c26e4867'), 12669)
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', 'winter_math::polynom::interpolate_batch::hb8afdf01fc3a097d', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12'), 12288)
(('alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::h6f1c7cfbf12cc11f', 'memmove', 'compiler_builtins::mem::memmove::ha1d81b2d3751da88'), 11072)
(('winter_math::fft::interpolate_poly::ha4bdeb398666aa90', 'winter_math::fft::serial::interpolate_poly::h4a43566481065096', 'winter_math::fft::serial::fft_in_place::hb7a1545ee2a0eee1'), 9350)
(('winter_math::polynom::interpolate_batch::hb8afdf01fc3a097d', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12', 'winter_math::field::f64::mont_red_cst::h4a0e8151c26e4867'), 9188)
(('risc0_zkvm_guest::sha::digest_u8_slice::h16754d6da2ff763a', 'memcpy', 'compiler_builtins::mem::memcpy::hba8731a4c8e62e30'), 8573)
(('<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::exp::h8a2c77ac6c62f624', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12', 'winter_math::field::f64::mont_red_cst::h4a0e8151c26e4867'), 7389)
(('<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::h7eac9395cb8fb2d0', 'winter_math::field::f64::exp_acc::h3705b31690abbccc', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12'), 7168)
(('<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::h7eac9395cb8fb2d0', 'winter_math::field::f64::exp_acc::hf4aae42cab3c08a5', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12'), 6656)
(('core::fmt::num::imp::fmt_u64::h955bda630abb3b10', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', 'winter_math::polynom::interpolate_batch::hb8afdf01fc3a097d'), 5420)
(('winter_math::field::f64::exp_acc::h3705b31690abbccc', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12', 'winter_math::field::f64::mont_red_cst::h4a0e8151c26e4867'), 5370)
(('winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4cd155375147fe75', 'winter_fri::verifier::channel::VerifierChannel::read_layer_queries::hf9f1250f02f1a32d', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h4a9acce079b79dce'), 5089)
(('winter_math::field::f64::exp_acc::hf4aae42cab3c08a5', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::ha4f2a52b536b9d12', 'winter_math::field::f64::mont_red_cst::h4a0e8151c26e4867'), 4989)
(('risc0_zkvm_guest::sha::digest_u8_slice::h16754d6da2ff763a', 'memset', 'compiler_builtins::mem::memset::h94eecc2afbdbd211'), 4959)
```

**Comment by starkoracles** [comment]
```
➜  risc0_profiling_tool git:(small-changes-and-bugfixes) ✗ pipenv run python3 prof.py
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_math::polynom::interpolate_batch::h6de5019d53d1f73a', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::h2415d8ae6edcae43'), 12288)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_fri::verifier::verify_remainder::h94089e3a2bf608b2', 'winter_math::fft::interpolate_poly::h250de23f543dd44b', 'winter_math::fft::serial::interpolate_poly::hda72d8020909d039', 'winter_math::fft::serial::fft_in_place::h07d2d38653846394'), 9350)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_math::polynom::interpolate_batch::h6de5019d53d1f73a', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::h2415d8ae6edcae43', 'winter_math::field::f64::mont_red_cst::h0b0c09944f3d9b8c'), 9188)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_math::polynom::interpolate_batch::h6de5019d53d1f73a'), 5420)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_fri::verifier::channel::VerifierChannel::read_layer_queries::hc7da60f03fb0854b', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h8decc0d2ecea5ac9'), 5089)
(('_start', '__start', '__main', 'winter_verifier::composer::DeepComposer<E>::compose_trace_columns::ha875f653b9e60956', '<winter_math::field::f64::BaseElement as core::ops::arith::Div>::div::h21ae7991a4e0f874', '<winter_math::field::f64::BaseElement as winter_math::field::traits::FieldElement>::inv::hc9893e7f024fdd1a', 'winter_math::field::f64::exp_acc::ha1babc9f571a30d8', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::h2415d8ae6edcae43'), 4224)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_fri::verifier::verify_remainder::h94089e3a2bf608b2', 'winter_math::fft::interpolate_poly::h250de23f543dd44b', 'winter_math::fft::serial::interpolate_poly::hda72d8020909d039', 'winter_math::fft::serial::fft_in_place::h07d2d38653846394', '<winter_math::field::f64::BaseElement as core::ops::arith::Mul>::mul::h2415d8ae6edcae43'), 4128)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_math::polynom::interpolate_batch::h6de5019d53d1f73a', '<winter_math::field::f64::BaseElement as core::ops::arith::Add>::add::h3f32e848d4cce005'), 4066)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_fri::verifier::verify_remainder::h94089e3a2bf608b2', 'winter_math::fft::interpolate_poly::h250de23f543dd44b', 'winter_math::fft::serial::interpolate_poly::hda72d8020909d039', 'winter_math::fft::permute_index::h3563cc9560e94dc1'), 4032)
(('_start', '__start', '__main', 'winter_verifier::channel::VerifierChannel<E,H>::read_queried_trace_states::h1ac3ff46e870db35', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h8decc0d2ecea5ac9', 'alloc::collections::btree::map::BTreeMap<K,V>::insert::h2e799b375846d55b', 'alloc::collections::btree::map::entry::VacantEntry<K,V>::insert::h2b9067b285e35718', 'alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::h5814c68b757ea245', 'memmove', 'compiler_builtins::mem::memmove::h24edc3f28882d433'), 3806)
(('_start', '__start', '__main', 'winter_verifier::channel::VerifierChannel<E,H>::read_constraint_evaluations::he7590044e24a5117', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h8decc0d2ecea5ac9', 'alloc::collections::btree::map::BTreeMap<K,V>::insert::h2e799b375846d55b', 'alloc::collections::btree::map::entry::VacantEntry<K,V>::insert::h2b9067b285e35718', 'alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::h5814c68b757ea245', 'memmove', 'compiler_builtins::mem::memmove::h24edc3f28882d433'), 3806)
(('_start', '__start', '__main', 'winter_verifier::channel::VerifierChannel<E,H>::read_queried_trace_states::h1ac3ff46e870db35', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h8decc0d2ecea5ac9'), 3789)
(('_start', '__start', '__main', 'winter_verifier::channel::VerifierChannel<E,H>::read_constraint_evaluations::he7590044e24a5117', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h8decc0d2ecea5ac9'), 3789)
(('__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_fri::verifier::channel::VerifierChannel::read_layer_queries::hc7da60f03fb0854b', 'winter_crypto::merkle::proofs::BatchMerkleProof<H>::get_root::h8decc0d2ecea5ac9', 'alloc::collections::btree::map::BTreeMap<K,V>::insert::h2e799b375846d55b', 'alloc::collections::btree::map::entry::VacantEntry<K,V>::insert::h2b9067b285e35718', 'alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing::h5814c68b757ea245', 'memmove', 'compiler_builtins::mem::memmove::h24edc3f28882d433'), 3460)
(('_start', '__start', '__main', 'winter_fri::verifier::FriVerifier<B,E,C,H>::verify::h4326619ba5ba1979', 'winter_fri::verifier::verify_remainder::h94089e3a2bf608b2', 'winter_math::fft::interpolate_poly::h250de23f543dd44b', 'winter_math::fft::serial::interpolate_poly::hda72d8020909d039', 'winter_math::fft::serial::fft_in_place::h07d2d38653846394', '<winter_math::field::f64::BaseElement as core::ops::arith::Add>::add::h3f32e848d4cce005'), 3207)
```

@maxgillett

**Pull request merged**
